# Generated by Django 4.2.4 on 2023-08-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpyou", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=128, verbose_name="유저 이메일"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="fullname",
            field=models.CharField(max_length=16, verbose_name="유저 이름"),
        ),
    ]
