# Generated by Django 4.2.4 on 2023-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpyou", "0002_alter_customuser_email_alter_customuser_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(max_length=100, verbose_name="유저 주소"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="day",
            field=models.CharField(max_length=2, verbose_name="유저 생년월일-일"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="detailed_address",
            field=models.CharField(max_length=100, verbose_name="유저 상세주소"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="month",
            field=models.CharField(max_length=2, verbose_name="유저 생년월일-월"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=13, verbose_name="유저 전화번호"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="year",
            field=models.CharField(max_length=4, verbose_name="유저 생년월일-년도"),
        ),
    ]
